jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://localhost:4243"
        readTimeout: 60
      name: "docker"
      templates:
      - connector:
          ssh:
            sshKeyStrategy:
              injectSSHKey:
                user: "root"
        dockerTemplateBase:
          image: "bibinwilson/jenkins-slave:latest"
        labelString: "docker"
        pullTimeout: 300
        remoteFs: "/home/jenkins"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm: # (2)
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        password: "admin"
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
jobs:
  - script: >
      folder('testjobs')
  - script: >
      pipelineJob('testjobs/default-agent') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }